/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConnectionFactory;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;

/**
 *
 * @author jarde
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        
        
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_sidebar = new javax.swing.JPanel();
        lbl_04 = new javax.swing.JLabel();
        lbl_03 = new javax.swing.JLabel();
        lbl_01 = new javax.swing.JLabel();
        lbl_02 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_5 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro");
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnl_sidebar.setBackground(new java.awt.Color(34, 41, 50));
        pnl_sidebar.setForeground(new java.awt.Color(255, 255, 255));
        pnl_sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_sidebarMouseDragged(evt);
            }
        });
        pnl_sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_sidebarMousePressed(evt);
            }
        });

        lbl_04.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_04.setForeground(new java.awt.Color(166, 166, 166));
        lbl_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/icons8-mais-25.png"))); // NOI18N
        lbl_04.setText("Cadastrar Alunos");
        lbl_04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_04MousePressed(evt);
            }
        });

        lbl_03.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_03.setForeground(new java.awt.Color(166, 166, 166));
        lbl_03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/icons8-mais-25.png"))); // NOI18N
        lbl_03.setText("Cadastrar Professores");
        lbl_03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_03MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_03MousePressed(evt);
            }
        });

        lbl_01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_01.setForeground(new java.awt.Color(166, 166, 166));
        lbl_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/icons8-cardápio-25.png"))); // NOI18N
        lbl_01.setText("Visualizar Alunos");
        lbl_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_01MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_01MousePressed(evt);
            }
        });

        lbl_02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_02.setForeground(new java.awt.Color(166, 166, 166));
        lbl_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/icons8-cardápio-25.png"))); // NOI18N
        lbl_02.setText("Visualizar Professores");
        lbl_02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_02MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_02MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/iconIFPA_1.png"))); // NOI18N

        lbl_5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_5.setForeground(new java.awt.Color(166, 166, 166));
        lbl_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/icons8-finn-25.png"))); // NOI18N
        lbl_5.setText("Sobre");
        lbl_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnl_sidebarLayout = new javax.swing.GroupLayout(pnl_sidebar);
        pnl_sidebar.setLayout(pnl_sidebarLayout);
        pnl_sidebarLayout.setHorizontalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_sidebarLayout.createSequentialGroup()
                        .addGroup(pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_01, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_04, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_03))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_sidebarLayout.setVerticalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_01, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_02, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_03, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_04, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane2.setBackground(new java.awt.Color(102, 102, 102));
        jDesktopPane2.setToolTipText("Desenvolvido Por Jardel Castro");
        jDesktopPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDesktopPane2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(54, 63, 73));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/icons8-fechar-janela-filled-25.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesHome/icons8-minimizar-janela-filled-25.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 867, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnl_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane2))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnl_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int xx;
    int xy;
    private void jDesktopPane2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane2MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jDesktopPane2MouseReleased

    private void lbl_01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_01MousePressed

         setLblColor(lbl_01);
         resetLblColor(lbl_02);
         resetLblColor(lbl_03);
         resetLblColor(lbl_04);
         resetLblColor(lbl_5);
        
        
    }//GEN-LAST:event_lbl_01MousePressed

    private void lbl_02MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_02MousePressed
         setLblColor(lbl_02);
         resetLblColor(lbl_01);
         resetLblColor(lbl_03);
         resetLblColor(lbl_04);
         resetLblColor(lbl_5);
    }//GEN-LAST:event_lbl_02MousePressed

    private void lbl_03MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03MousePressed
         setLblColor(lbl_03);
         resetLblColor(lbl_02);
         resetLblColor(lbl_01);
         resetLblColor(lbl_04);
         resetLblColor(lbl_5);
    }//GEN-LAST:event_lbl_03MousePressed

    private void lbl_04MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04MousePressed
         setLblColor(lbl_04);
         resetLblColor(lbl_02);
         resetLblColor(lbl_03);
         resetLblColor(lbl_01);
         resetLblColor(lbl_5);
    }//GEN-LAST:event_lbl_04MousePressed

    private void pnl_sidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sidebarMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnl_sidebarMousePressed

    private void pnl_sidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnl_sidebarMouseDragged

    private void lbl_01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_01MouseClicked
        try{
        TabelaAluno TelaAluno = new TabelaAluno();
        jDesktopPane2.add(TelaAluno);
        TelaAluno.setVisible(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Falha no Carregamento do Banco de Dados");
        }
    }//GEN-LAST:event_lbl_01MouseClicked

    private void lbl_02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_02MouseClicked
        try{
        TabelaProfessor TelaProfessor = new TabelaProfessor();
        jDesktopPane2.add(TelaProfessor);
        TelaProfessor.setVisible(true);  
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Falha no Carregamento do Banco de Dados");
        }
    }//GEN-LAST:event_lbl_02MouseClicked

    private void lbl_03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03MouseClicked
        try{
        TelaCadastroProfessor TelaCadProfessor = new TelaCadastroProfessor();
        jDesktopPane2.add(TelaCadProfessor);
        TelaCadProfessor.setVisible(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Falha no Carregamento do Banco de Dados");
        }
    }//GEN-LAST:event_lbl_03MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.PLAIN, 14));
        int i = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?","Verifcação de saida",JOptionPane.YES_OPTION);
        if(i == JOptionPane.YES_OPTION){
        System.exit(0);}
        else{
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        setExtendedState(TelaLogin.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
       
    }//GEN-LAST:event_jPanel2MouseDragged

    private void lbl_04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04MouseClicked
        // TODO add your handling code here:
        try{
        TelaCadastroAluno TelaCadAluno = new TelaCadastroAluno();
        jDesktopPane2.add(TelaCadAluno);
        TelaCadAluno.setVisible(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Falha no Carregamento do Banco de Dados");
        }
       
    }//GEN-LAST:event_lbl_04MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Bem vindo ao Sistema de Cadastro de Usuários");
        JOptionPane.showMessageDialog(null, "A sua esquerda você pode escolher as opções\n"
                + "de cadastro do tipo aluno ou professor"
                + "e as \ntabelas de registros do tipo professor, aluno.");
    }//GEN-LAST:event_formWindowOpened

    private void lbl_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_5MouseClicked
        // TODO add your handling code here:
        new Sobre().setVisible(true);
    }//GEN-LAST:event_lbl_5MouseClicked

    private void lbl_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_5MousePressed
        // TODO add your handling code here:
        setLblColor(lbl_5);
         resetLblColor(lbl_02);
         resetLblColor(lbl_03);
         resetLblColor(lbl_01);
         resetLblColor(lbl_04);
    }//GEN-LAST:event_lbl_5MousePressed

    public void setLblColor(JLabel lbl) {
        lbl.setForeground(new Color(48, 201, 235));
    }

    public void resetLblColor(JLabel lbl) {
        lbl.setForeground(new Color(166, 166, 166));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_01;
    private javax.swing.JLabel lbl_02;
    private javax.swing.JLabel lbl_03;
    private javax.swing.JLabel lbl_04;
    private javax.swing.JLabel lbl_5;
    private javax.swing.JPanel pnl_sidebar;
    // End of variables declaration//GEN-END:variables
}
